# docker-composeのバージョン
version: "3"

# コンテナ定義
services:

  # webサーバー
  web:
    # コンテナ名
    container_name: "web-api"
    # コンテナの作成に使用するDockerfileのパス
    build:
      dockerfile: "./docker/web/Dockerfile"
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "8080:80"
#      - "8000:8000"
    # src配下のファイルをコンテナ内の~/var/www/html配下に配置
    volumes:
        - ./:/var/www/html
        - ./docker/web/local/default.conf:/etc/nginx/conf.d/default.conf

  # PHPサーバー
  php:
    # コンテナ名
    container_name: "php-api"
    # コンテナの作成に使用するDockerfileのパス
    build:
      dockerfile: "./docker/php/Dockerfile"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    environment:
      - USER_NAME
      - USER_ID
      - GROUP_NAME
      - GROUP_ID
    volumes:
        - ./:/var/www/html
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  #   DBサーバー
  db:
    # コンテナ名
    container_name: "my-db"
    # コンテナの作成に使用するDockerfileのパス
    build:
      dockerfile: "./docker/db/Dockerfile"
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "3306:3306"
    # 環境変数の指定
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=dev"
      - "MYSQL_PASSWORD=dev"
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/data:/var/lib/mysql
